import LinkedinApis from "../services/linkedinApis.js"

const createLinkedInPost = async (userUrn, img_urn, postContent) => {
  try {

    const text = `This post author is \x1b[1m${postContent.author}\x1b[0m \n This Post is generated by http://github.com/DSDmark/AutoScript \n check out my github if you want to know more about AutoScript`;

    const post = {
      "author": `urn:li:person:${userUrn}`,
      "lifecycleState": "PUBLISHED",
      "specificContent": {
        "com.linkedin.ugc.ShareContent": {
          "shareCommentary": {
            "text": `${postContent.title}\n ${text}\n #${postContent.subreddit} #${postContent.author}`,
          },

          "shareMediaCategory": "IMAGE",
          "media": [
            {
              "status": "READY",
              "title": {
                "text": postContent.title,
              }, "media": `urn:li:digitalmediaAsset:${img_urn}`
            }
          ],
        }
      },
      "visibility": {
        "com.linkedin.ugc.MemberNetworkVisibility": "CONNECTIONS"
      }
    }

    const res = await LinkedinApis.createPost(post);
    console.log('LinkedIn post created successfully:', res.data);
  } catch (error) {
    console.error('Error creating LinkedIn post:', error);
  }
}

export default createLinkedInPost;
