import LinkedinApis from "../services/linkedinApis.js"

const createLinkedInPost = async (userUrn, img_urn, postContent) => {
  try {

    const repoName = "AutoScript"
    const githubRepoLink = `http://github.com/DSDmark/${repoName}`
    const text = `This post author is ${postContent.author}. This Post is generated by 🚀${repoName}🚀 \n if you want to know more about AutoScript:${githubRepoLink}`;

    const post = {
      "author": `urn:li:person:${userUrn}`,
      "lifecycleState": "PUBLISHED",
      "specificContent": {
        "com.linkedin.ugc.ShareContent": {
          "shareCommentary": {
            "text": `${postContent.title}\n \n \n ${text}\n \n #${postContent.subreddit} #${postContent.author}`,
          },
          "shareMediaCategory": "IMAGE",
          "media": [
            {
              "status": "READY",
              "title": {
                "text": postContent.title,
              }, "media": `urn:li:digitalmediaAsset:${img_urn}`
            }
          ],
        },

      },
      "visibility": {
        "com.linkedin.ugc.MemberNetworkVisibility": "CONNECTIONS"
      }
    }

    const res = await LinkedinApis.createPost(post);
    console.log('LinkedIn post created successfully:', res.data);
  } catch (error) {
    console.error('Error creating LinkedIn post:', error);
  }
}

export default createLinkedInPost;
