import LinkedinApis from "../services/linkedinApis.js"

const createLinkedInPost = async (userUrn, img_urn, postContent) => {
  try {

    const text = `This post author is <h3 color="green">${postContent.author}</h3> This Post is generated by <a href='http://github.com/DSDmark/AutoScript'>AutoScript</a><br> check out my github if you want to know more about AutoScript`;

    const post = {
      "author": `urn:li:person:${userUrn}`,
      "lifecycleState": "PUBLISHED",
      "specificContent": {
        "com.linkedin.ugc.ShareContent": {
          "shareCommentary": {
            "text": `${postContent.title} ${text}`,
            "heshtags": [postContent.subreddit, postContent.author]
          },
          "shareMediaCategory": "IMAGE",
          "media": [
            {
              "status": "READY",
              "description": {
                "text": postContent.title,
              }, "media": `urn:li:digitalmediaAsset:${img_urn}`
            }
          ]
        }
      },
      "visibility": {
        "com.linkedin.ugc.MemberNetworkVisibility": "CONNECTIONS"
      }
    }

    const res = await LinkedinApis.createPost(post);
    console.log('LinkedIn post created successfully:', res.data);
  } catch (error) {
    console.error('Error creating LinkedIn post:', error);
  }
}

export default createLinkedInPost;
